import re
import sqlite3
import time
from database import init_db, DB_NAME

TXT_FILE = "verified_users.txt"
DB_FILE = DB_NAME
PROMOTION_SECONDS = 14 * 24 * 60 * 60

HEADER_MARKERS = (
    "BLADES VERIFIED",
    "Version:",
    "Generated:",
    "-----",
    "====",
    "Generated by BLADES",
)

LINE_PATTERN = re.compile(r"^(.*?)\s*\((\d+)\)\s*-\s*(.*)$")


def parse_verified_users_file(path):
    parsed = {}

    with open(path, "r", encoding="utf-8") as file:
        for raw_line in file:
            line = raw_line.strip()
            if not line:
                continue
            if any(marker in line for marker in HEADER_MARKERS):
                continue

            match = LINE_PATTERN.match(line)
            if not match:
                continue

            username, user_id, source = match.groups()
            parsed[user_id] = {
                "username": username,
                "raw_source": source,
            }

    return parsed


def ensure_schema(conn):
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            user_id TEXT PRIMARY KEY,
            username TEXT NOT NULL,
            status TEXT NOT NULL,
            first_seen_ts INTEGER NOT NULL,
            bought_tag INTEGER NOT NULL DEFAULT 0
        )
        """
    )
    conn.commit()


def load_existing(conn):
    cur = conn.cursor()
    cur.execute("SELECT user_id, username, status, first_seen_ts, bought_tag FROM users")
    return {
        row[0]: {
            "username": row[1],
            "status": row[2],
            "first_seen_ts": int(row[3]),
            "bought_tag": int(row[4]),
        }
        for row in cur.fetchall()
    }


def determine_status(raw_source, existing_row, now_ts):
    if raw_source == "Seed List":
        return "Seed List"

    if existing_row:
        if existing_row["status"] == "Seed List":
            return "Seed List"

        age = now_ts - int(existing_row["first_seen_ts"])
        if age >= PROMOTION_SECONDS:
            return "Seed List"

    return "Newly Added"


def sync_database(parsed_rows):
    init_db()
    now_ts = int(time.time())

    conn = sqlite3.connect(DB_FILE)
    try:
        existing = load_existing(conn)
        cur = conn.cursor()

        for user_id, row in parsed_rows.items():
            old = existing.get(user_id)

            first_seen = old["first_seen_ts"] if old else now_ts
            bought_tag = old["bought_tag"] if old else 0
            status = determine_status(row["raw_source"], old, now_ts)

            cur.execute(
                """
                INSERT INTO users (user_id, username, status, first_seen_ts, bought_tag)
                VALUES (?, ?, ?, ?, ?)
                ON CONFLICT(user_id) DO UPDATE SET
                    username=excluded.username,
                    status=excluded.status,
                    first_seen_ts=excluded.first_seen_ts,
                    bought_tag=excluded.bought_tag
                """,
                (user_id, row["username"], status, int(first_seen), int(bought_tag)),
            )

        current_ids = set(parsed_rows.keys())
        stale_ids = [uid for uid in existing.keys() if uid not in current_ids]
        if stale_ids:
            cur.executemany("DELETE FROM users WHERE user_id=?", [(uid,) for uid in stale_ids])

        conn.commit()

        cur.execute("SELECT COUNT(*) FROM users")
        total = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM users WHERE status='Seed List'")
        seed_total = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM users WHERE status='Newly Added'")
        new_total = cur.fetchone()[0]

        print("Database sync complete.")
        print(f"Total users: {total}")
        print(f"Seed List users: {seed_total}")
        print(f"Newly Added users: {new_total}")
    finally:
        conn.close()


def main():
    parsed = parse_verified_users_file(TXT_FILE)
    sync_database(parsed)


if __name__ == "__main__":
    main()
